resolver: nightly-2017-12-13

packages:
- .

allow-newer: true

extra-deps:
- toysolver-0.5.0
- OptDir-0.0.3
- data-interval-1.3.0
- extended-reals-0.2.2.0
- finite-field-0.9.0
- pseudo-boolean-0.1.6.0
- queue-0.1.2
- sign-0.4.3
- combinat-0.2.8.2
- permutation-0.5.0.5
